# Generated by Django 5.1.5 on 2025-04-29 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0024_user_foto_perfil'),
        ('notificacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacaoadmin',
            name='grupo_destinatario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes_admin', to='auth.group'),
            preserve_default=False,
        ),
    ]
