# Generated by Django 5.1.5 on 2025-04-09 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energia_consumida_kwh', models.FloatField(default=0.0, help_text='Valor da energia consumida em kwh', verbose_name='Energia consumida em kwh')),
                ('energia_restante_kwh', models.FloatField(default=0.0, help_text='Valor da energia restante em kwh', verbose_name='Energia restante em kwh')),
                ('energia_comprada_kwh', models.FloatField(default=0.0, help_text='Valor da energia comprada em kwh', verbose_name='Energia comprada em kwh')),
                ('energia_consumida_kzs', models.FloatField(default=0.0, help_text='Valor da energia consumida em kzs', verbose_name='Energia consumida em kzs')),
                ('energia_restante_kzs', models.FloatField(default=0.0, help_text='Valor da energia restante em kzs', verbose_name='Energia restante em kzs')),
                ('energia_comprada_kzs', models.FloatField(default=0.0, help_text='Valor da energia comprada em kzs', verbose_name='Energia comprada em kzs')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.residencia')),
            ],
        ),
    ]
