# Generated by Django 5.1.5 on 2025-04-10 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicao',
            name='residencia',
        ),
        migrations.AddField(
            model_name='medicao',
            name='status',
            field=models.BooleanField(default=False, help_text='Estado do relé: ON/OFF', verbose_name='Estado'),
        ),
    ]
