# Generated by Django 5.1.5 on 2025-04-22 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_remove_residencia_medicao'),
        ('medicao', '0002_remove_medicao_residencia_medicao_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicao',
            name='residencia',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='medicao', to='cadastro.residencia'),
            preserve_default=False,
        ),
    ]
