# Generated by Django 5.1.5 on 2025-04-23 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_mensagem_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('enviada', '✓'), ('recebida', '✓'), ('enviada', '✓'), ('visualizada', '✓✓ azul')], default='enviada', max_length=15),
        ),
    ]
