# Generated by Django 5.1.5 on 2025-04-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_mensagem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensagem',
            name='status',
            field=models.CharField(choices=[('enviada', '✓'), ('recebida', '✓✓'), ('visualizada', '✓✓ azul')], default='enviada', max_length=15),
        ),
    ]
