# Generated by Django 5.1.5 on 2025-03-05 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pt', models.CharField(max_length=255, unique=True, verbose_name='Nome do PT')),
                ('numero_pt', models.IntegerField(unique=True, verbose_name='Numero do PT')),
                ('municipio_pt', models.CharField(max_length=255, verbose_name='Município')),
                ('bairro_pt', models.CharField(max_length=255, verbose_name='Bairro')),
                ('data_pt', models.DateTimeField(auto_now=True, verbose_name='Data de cadastramento')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_post', models.CharField(max_length=255, verbose_name='Nome do Post')),
                ('numero_post', models.IntegerField(verbose_name='Numero do Post')),
                ('rua_post', models.CharField(max_length=255, verbose_name='Rua')),
                ('data_post', models.DateTimeField(auto_now=True)),
                ('pt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cadastro.pt', verbose_name='Posto de Transformação(PT)')),
            ],
            options={
                'unique_together': {('numero_post', 'pt')},
            },
        ),
        migrations.CreateModel(
            name='Residencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_residencia', models.IntegerField(verbose_name='Numero da Residência')),
                ('nome_proprietario', models.CharField(max_length=255, verbose_name='Proprietário')),
                ('endereco_residencia', models.CharField(help_text='Endereço', max_length=255, verbose_name='Endereço')),
                ('energia_comprada', models.FloatField(default=0.0, help_text='Valor da energia comprada', verbose_name='Energia comprada')),
                ('energia_activa', models.FloatField(default=0.0, help_text='Valor da energia activa', verbose_name='Energia activa')),
                ('energia_consumida', models.FloatField(default=0.0, help_text='Valor da energia consumida', verbose_name='Energia consumida')),
                ('status', models.BooleanField(default=False, help_text='Estado do relé: ON/OFF', verbose_name='Estado')),
                ('ativo_residencia', models.BooleanField(default=True, verbose_name='Residência no activo')),
                ('data_residencia', models.DateTimeField(auto_now_add=True, verbose_name='Data de registro')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to='cadastro.post')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('numero_residencia', 'post')},
            },
        ),
    ]
