# Generated by Django 5.1.5 on 2025-04-10 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('medicao', '0002_remove_medicao_residencia_medicao_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='energia_activa',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='energia_comprada',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='energia_consumida',
        ),
        migrations.RemoveField(
            model_name='residencia',
            name='status',
        ),
        migrations.AddField(
            model_name='residencia',
            name='endereco_gateway',
            field=models.CharField(default=0, max_length=255, verbose_name='Gateway Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='residencia',
            name='medicao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='medição', to='medicao.medicao'),
            preserve_default=False,
        ),
    ]
