# Generated by Django 5.1.5 on 2025-04-12 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_remove_residencia_energia_activa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residencias', to='cadastro.post'),
        ),
    ]
