# Generated by Django 5.1.5 on 2025-04-12 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_alter_residencia_post_alter_residencia_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='usuario',
        ),
    ]
