# Generated by Django 5.1.5 on 2025-04-14 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_residencia_usuario'),
        ('medicao', '0002_remove_medicao_residencia_medicao_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='endereco_gateway',
        ),
        migrations.AddField(
            model_name='residencia',
            name='endereco_esp32',
            field=models.CharField(default=2, max_length=255, verbose_name='Esp32 Endereço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='residencia',
            name='medicao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medição', to='medicao.medicao'),
        ),
        migrations.AlterField(
            model_name='residencia',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residencia', to=settings.AUTH_USER_MODEL),
        ),
    ]
