# Generated by Django 5.1.5 on 2025-04-21 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_residencia_endereco_gateway_and_more'),
        ('medicao', '0002_remove_medicao_residencia_medicao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residencia',
            name='medicao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medição', to='medicao.medicao'),
        ),
    ]
