# Generated by Django 5.1.5 on 2025-04-22 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_residencia_medicao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residencia',
            name='medicao',
        ),
    ]
