# Generated by Django 5.1.5 on 2025-04-09 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoEnergia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_transacao', models.CharField(choices=[('COMPRA', 'Compra'), ('CONSUMO', 'Consumo')], max_length=50)),
                ('quatidade_kwh', models.FloatField(default=0.0, help_text='Valor da energia em kwh', verbose_name='Energia em Kwh')),
                ('valor_energia_kzs', models.FloatField(default=0.0, help_text='Valor da energia em kzs', verbose_name='Energia em Kzs')),
                ('data_transacao', models.DateTimeField(auto_now_add=True)),
                ('residencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.residencia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
