# Generated by Django 5.1.5 on 2025-05-08 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pagamento',
        ),
    ]
