"""
Django settings for medidor project.

Generated by 'django-admin startproject' using Django 5.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os.path
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-msxj_)f+#2)3)%wb_j_&c#&rpf5bjnfq_8wy#+=uut*!p7n(9a'

#Para garantir que o django redirecione automaticamente as requisições HTTP para
# HTTPS, basta adicionar:
#SECURE_SSL_REDIRECT = True
#SECURE_COOKIE = True
#SESSION_COOKIE_SECURE = True

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'channels',
    'rest_framework',
    'paginas.apps.PaginasConfig',
    'cadastro.apps.CadastroConfig',
    'notificacao.apps.NotificacaoConfig',
    'usuario.apps.UsuarioConfig',
    'chat.apps.ChatConfig',
    'pagamento.apps.PagamentoConfig',
    'historico.apps.HistoricoConfig',
    'medicao.apps.MedicaoConfig',
]

CRISPY_TEMPLATES_PACK = 'bootstrap4'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuario.middleware.StatusUsuarioMiddleware',
]

ROOT_URLCONF = 'medidor.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

                # Ativando apps criadas pelo programador
            ],
        },
    },
]
WSGI_APPLICATION = 'medidor.wsgi.application'

ASGI_APPLICATION = 'medidor.asgi.application'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'pt-ao'

TIME_ZONE = 'Africa/Luanda'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'

# Identificando o diretório dos arquivos estaticos
# para que todos os modulos tenham acesso a ele
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]


# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


# Configurações de Autenticação
#AUTH_USER_MODEL = 'cadastro.Usuario' #Quando criamos o nosso models de usuarioa
LOGIN_REDIRECT_URL = '/'# Após o login onde o usuario vai para...usando '/' estamos a dizer

#que a logica de redirecionamento seja sobreposto pela logica da views
LOGOUT_REDIRECT_URL = 'index' # Após o logout onde a pagina e renderizada

LOGIN_URL = 'index'
# Quando a pessoa não tem acesso a uma pagina sera renderizada aqui
#Poderiamos criar uma pagina de ajuda a informar sobre o assunto

'''
# Configurando Twilio
TWILIO_ACCOUNT_SID = 'ACf8bad53a9cd82df5f182a3'
TWILIO_AUTH_TOKEN = '3df6002ed53a1b1230b1'
TWILIO_PHONE_NUMBER = '+244 948629771'
'''

#Configurando Serviços de Email
DEFAULT_FROM_EMAIL = 'gonga396@gmal.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gonga396@gmail.com'
EMAIL_HOST_PASSWORD = 'Ti10ad11ad12bd$'

'''
#Configurando PayPal
PAYPAL_CLIENT_ID = "AYcvUimTtlwQG7PiWisWCKjx1uO_lhOYS4wLa9R3uZMeIERn6leeR8LoPZ0zeT-9tExBp6UMONxhE9K9"
PAYPAL_CLIENT_SECRET = "EFdATyf87XfE-eMw4JR6FjQvY4eD2fLI_PKCOjY_dxdj-ieLAtjQE8PaA_hiQveJEcZ-yeRcytEfQ3bQ"
PAYPAL_ENV = "sandbox"
PAYPAL_CURRENCY = "USD" #Moeda definida como kwanza
PAYPAL_API_URL = "https://api.sandbox.paypal.com" if PAYPAL_ENV == "sandbox" else "http://api.paypal.com"
PAGAMENTO_MINIMO_KZ = 1.00
ESP32_API_URL = 'http://esp32_local_ip/api'
'''

